#!/usr/bin/env bash
#prints 'Best School' 10 times
#but the after the 9th iteration 'Hi' is printed on the new line

i=0
while [ $i -lt 11 ]
do
  if [ $i == 9 ]
  then
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))
done
