#!/usr/bin/env bash
#changes the home IP
cp /etc/hosts /home/hosts.txt
echo "127.0.0.2       localhost" > /home/hosts.txt
echo "8.8.8.8         facebook.com" >> /home/hosts.txt
cp /home/hosts.txt /etc/hosts
