#!/usr/bin/env bash
# Install and configure HAProxy load balancer to 31769-lb-01
# sends traffic to web-01 and web-02


CONFGF="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 31769-web-01 54.90.12.170 check\n\tserver 31769-web-02 100.26.238.177 check\n"

sudo apt-get update
sudo apt-get -y install nginx
#version 1.5 and above
sudo apt-get install -y haproxy
#enable HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
# include roundrobin and two servers
sudo sed -i "\$a $CONFGF" /etc/haproxy/haproxy.cfg

sudo service haproxy start

